/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package student_management_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class AddProgram extends javax.swing.JFrame {

    /**
     * Creates new form AddProgram
     */
    public AddProgram() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tfCourseName15 = new javax.swing.JTextField();
        tfCourseName16 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnAddLecturer = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfProgramName = new javax.swing.JTextField();
        tfProgramCode = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        tfUnit1Name = new javax.swing.JTextField();
        tfUnit1Id = new javax.swing.JTextField();
        tfUnit2Name = new javax.swing.JTextField();
        tfUnit2Id = new javax.swing.JTextField();
        tfUnit3Id = new javax.swing.JTextField();
        tfUnit3Name = new javax.swing.JTextField();
        tfUnit4Id = new javax.swing.JTextField();
        tfUnit4Name = new javax.swing.JTextField();
        tfUnit5Id = new javax.swing.JTextField();
        tfUnit5Name = new javax.swing.JTextField();

        jLabel17.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(164, 209, 209));
        jLabel17.setText("Unit 1 code");

        jLabel18.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(164, 209, 209));
        jLabel18.setText("Unit 1 name");

        tfCourseName15.setBackground(new java.awt.Color(51, 51, 51));
        tfCourseName15.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfCourseName15.setForeground(new java.awt.Color(164, 209, 209));
        tfCourseName15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCourseName15ActionPerformed(evt);
            }
        });

        tfCourseName16.setBackground(new java.awt.Color(51, 51, 51));
        tfCourseName16.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfCourseName16.setForeground(new java.awt.Color(164, 209, 209));
        tfCourseName16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCourseName16ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(36, 47, 54));

        jPanel3.setBackground(new java.awt.Color(41, 73, 94));
        jPanel3.setForeground(new java.awt.Color(164, 209, 209));

        jLabel1.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(164, 209, 209));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\Student_Management_System\\src\\images\\icons\\report.png")); // NOI18N
        jLabel1.setText("Add Course");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N

        btnAddLecturer.setBackground(new java.awt.Color(26, 59, 80));
        btnAddLecturer.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        btnAddLecturer.setForeground(new java.awt.Color(0, 0, 0));
        btnAddLecturer.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\Student_Management_System\\src\\images\\icons\\icons8-report-card-50.png")); // NOI18N
        btnAddLecturer.setText("Add Program");
        btnAddLecturer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAddLecturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLecturerActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(164, 209, 209));
        jLabel12.setText("  Back");

        lblBack.setBackground(new java.awt.Color(0, 0, 0));
        lblBack.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\Student_Management_System\\src\\images\\icons\\back icon.png")); // NOI18N
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(164, 209, 209));
        jLabel14.setText("Program Name");

        jLabel13.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(164, 209, 209));
        jLabel13.setText("Program Code");

        tfProgramName.setBackground(new java.awt.Color(51, 51, 51));
        tfProgramName.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfProgramName.setForeground(new java.awt.Color(164, 209, 209));
        tfProgramName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfProgramNameActionPerformed(evt);
            }
        });

        tfProgramCode.setBackground(new java.awt.Color(51, 51, 51));
        tfProgramCode.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfProgramCode.setForeground(new java.awt.Color(164, 209, 209));
        tfProgramCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfProgramCodeActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(164, 209, 209));
        jLabel15.setText("Unit 1 code");

        jLabel16.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(164, 209, 209));
        jLabel16.setText("Unit 1 name");

        jLabel19.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(164, 209, 209));
        jLabel19.setText("Unit 2 code");

        jLabel20.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(164, 209, 209));
        jLabel20.setText("Unit 2 name");

        jLabel21.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(164, 209, 209));
        jLabel21.setText("Unit 3 code");

        jLabel22.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(164, 209, 209));
        jLabel22.setText("Unit 3 name");

        jLabel23.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(164, 209, 209));
        jLabel23.setText("Unit 4 code");

        jLabel24.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(164, 209, 209));
        jLabel24.setText("Unit 4 name");

        jLabel25.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(164, 209, 209));
        jLabel25.setText("Unit 5 code");

        jLabel26.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(164, 209, 209));
        jLabel26.setText("Unit 5 name");

        tfUnit1Name.setBackground(new java.awt.Color(51, 51, 51));
        tfUnit1Name.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfUnit1Name.setForeground(new java.awt.Color(164, 209, 209));
        tfUnit1Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnit1NameActionPerformed(evt);
            }
        });

        tfUnit1Id.setBackground(new java.awt.Color(51, 51, 51));
        tfUnit1Id.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfUnit1Id.setForeground(new java.awt.Color(164, 209, 209));
        tfUnit1Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnit1IdActionPerformed(evt);
            }
        });

        tfUnit2Name.setBackground(new java.awt.Color(51, 51, 51));
        tfUnit2Name.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfUnit2Name.setForeground(new java.awt.Color(164, 209, 209));
        tfUnit2Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnit2NameActionPerformed(evt);
            }
        });

        tfUnit2Id.setBackground(new java.awt.Color(51, 51, 51));
        tfUnit2Id.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfUnit2Id.setForeground(new java.awt.Color(164, 209, 209));
        tfUnit2Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnit2IdActionPerformed(evt);
            }
        });

        tfUnit3Id.setBackground(new java.awt.Color(51, 51, 51));
        tfUnit3Id.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfUnit3Id.setForeground(new java.awt.Color(164, 209, 209));
        tfUnit3Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnit3IdActionPerformed(evt);
            }
        });

        tfUnit3Name.setBackground(new java.awt.Color(51, 51, 51));
        tfUnit3Name.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfUnit3Name.setForeground(new java.awt.Color(164, 209, 209));
        tfUnit3Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnit3NameActionPerformed(evt);
            }
        });

        tfUnit4Id.setBackground(new java.awt.Color(51, 51, 51));
        tfUnit4Id.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfUnit4Id.setForeground(new java.awt.Color(164, 209, 209));
        tfUnit4Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnit4IdActionPerformed(evt);
            }
        });

        tfUnit4Name.setBackground(new java.awt.Color(51, 51, 51));
        tfUnit4Name.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfUnit4Name.setForeground(new java.awt.Color(164, 209, 209));
        tfUnit4Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnit4NameActionPerformed(evt);
            }
        });

        tfUnit5Id.setBackground(new java.awt.Color(51, 51, 51));
        tfUnit5Id.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfUnit5Id.setForeground(new java.awt.Color(164, 209, 209));
        tfUnit5Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnit5IdActionPerformed(evt);
            }
        });

        tfUnit5Name.setBackground(new java.awt.Color(51, 51, 51));
        tfUnit5Name.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfUnit5Name.setForeground(new java.awt.Color(164, 209, 209));
        tfUnit5Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnit5NameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfProgramName, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfProgramCode, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(152, 422, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfUnit3Name))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfUnit2Name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfUnit2Id, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfUnit3Id, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfUnit1Id, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfUnit1Name))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfUnit5Id, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfUnit5Name, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfUnit4Name, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfUnit4Id, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddLecturer, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfProgramName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfProgramCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(67, 67, 67)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfUnit1Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16)
                                .addComponent(tfUnit1Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(jLabel24))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfUnit4Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfUnit4Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(tfUnit2Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfUnit3Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(tfUnit3Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addComponent(lblBack, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfUnit2Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfUnit5Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfUnit5Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddLecturer, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        // TODO add your handling code here:
        AdminPage admp = new AdminPage();
        admp.show();
        dispose();
    }//GEN-LAST:event_lblBackMouseClicked

    private void tfProgramNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfProgramNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfProgramNameActionPerformed

    private void tfProgramCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfProgramCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfProgramCodeActionPerformed

    private void tfCourseName15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCourseName15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCourseName15ActionPerformed

    private void tfCourseName16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCourseName16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCourseName16ActionPerformed

    private void tfUnit1NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnit1NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnit1NameActionPerformed

    private void tfUnit1IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnit1IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnit1IdActionPerformed

    private void tfUnit2NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnit2NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnit2NameActionPerformed

    private void tfUnit2IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnit2IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnit2IdActionPerformed

    private void tfUnit3IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnit3IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnit3IdActionPerformed

    private void tfUnit3NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnit3NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnit3NameActionPerformed

    private void tfUnit4IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnit4IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnit4IdActionPerformed

    private void tfUnit4NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnit4NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnit4NameActionPerformed

    private void tfUnit5IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnit5IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnit5IdActionPerformed

    private void tfUnit5NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnit5NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnit5NameActionPerformed

    private void btnAddLecturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLecturerActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/student_management_system", "root", "emarshKmax");
           // String sql="INSERT into student (regno, tfName, parentname, parentcontact, DOB, sex,countryOfOrigin, hometown, religion, programName, programId ) VALUES (?,?,?,?,?,?,?,?,?,?,?)";
            Statement st = con.createStatement();

             String programName = tfProgramName.getText();
             String programId = tfProgramCode.getText();
            String unit1name = tfUnit1Name.getText();
             String unit1Id= tfUnit1Id.getText();
             String unit2name= tfUnit2Name.getText();
             String unit2Id= tfUnit2Id.getText();
             String unit3name= tfUnit3Name.getText();
             String unit3Id= tfUnit3Id.getText();
             String unit4name= tfUnit4Name.getText();
             String unit4Id= tfUnit4Id.getText();
             String unit5name= tfUnit5Name.getText();
             String unit5id= tfUnit5Id.getText();
             st.executeUpdate("insert into program (ProgramName, ProgramId, Unit1Name, Unit1Id, Unit2Name, Unit2Id, Unit3Name, Unit3Id, Unit4Name, Unit4Id, Unit5Name, Unit5Id) values("+"\""+programName+"\""+","+"\""+programId+"\""+","+"\""+unit1name+"\""+","+"\""+unit1Id+"\""+","+"\""+unit2name+"\""+","+"\""+unit2Id+"\""+","+"\""+unit3name+"\""+","+"\""+unit3Id+"\""+","+"\""+unit4name+"\""+","+"\""+unit4Id+"\""+","+"\""+unit5name+"\""+","+"\""+unit5id+"\""+");");
            
           /* PreparedStatement pst=conn.prepareStatement(sql);
            pst.setString(1,tfRegNumber.getText());
            pst.setString(2,tfname.getText());
            pst.setString(3,tfParent.getText());
            pst.setString(4, tfParentContact.getText());
            pst.setString(5, tfDateOfBirth.getText());
            pst.setString(6, (String) cbSex.getSelectedItem());
            pst.setString(7,tfCountryOfOrigin.getText());
            pst.setString(8,tfHometown.getText());
            pst.setString(9,tfReligion.getText());
            pst.setString(10,tfProgramName.getText());
            pst.setString(11,tfProgramCode.getText());
            int rowsInserted=pst.executeUpdate();   */
           // if(rowsinserted>0){
                JOptionPane.showMessageDialog(null,"Program Added Succesfully");
                
            //}
          //else  {
            //    JOptionPane.showMessageDialog(null,"Error Adding Student" );
            //}
           
            con.close();
            st.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_btnAddLecturerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProgram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddLecturer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblBack;
    private javax.swing.JTextField tfCourseName15;
    private javax.swing.JTextField tfCourseName16;
    private javax.swing.JTextField tfProgramCode;
    private javax.swing.JTextField tfProgramName;
    private javax.swing.JTextField tfUnit1Id;
    private javax.swing.JTextField tfUnit1Name;
    private javax.swing.JTextField tfUnit2Id;
    private javax.swing.JTextField tfUnit2Name;
    private javax.swing.JTextField tfUnit3Id;
    private javax.swing.JTextField tfUnit3Name;
    private javax.swing.JTextField tfUnit4Id;
    private javax.swing.JTextField tfUnit4Name;
    private javax.swing.JTextField tfUnit5Id;
    private javax.swing.JTextField tfUnit5Name;
    // End of variables declaration//GEN-END:variables
}
