/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package student_management_system;


import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class AddStudent extends javax.swing.JFrame {

    /**
     * Creates new form AddStudent
     */
    public AddStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tfUnit2 = new javax.swing.JPanel();
        tfname = new javax.swing.JTextField();
        tfParent = new javax.swing.JTextField();
        tfParentContact = new javax.swing.JTextField();
        tfDateOfBirth = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfCountryOfOrigin = new javax.swing.JTextField();
        tfHometown = new javax.swing.JTextField();
        tfReligion = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfProgramName = new javax.swing.JTextField();
        tfProgramCode = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tfRegNumber = new javax.swing.JTextField();
        pfPassword = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cbSex = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfUnit1Name = new javax.swing.JTextField();
        tfUnit2Name = new javax.swing.JTextField();
        tfUnit3Name = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tfUnit4Name = new javax.swing.JTextField();
        tfUnit5Name = new javax.swing.JTextField();
        tfUnit4Id = new javax.swing.JTextField();
        tfUnit5Id = new javax.swing.JTextField();
        tfUnit1Id = new javax.swing.JTextField();
        tfUnit2Id = new javax.swing.JTextField();
        tfUnit3Id = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(41, 73, 94));

        jPanel2.setBackground(new java.awt.Color(36, 47, 54));
        jPanel2.setForeground(new java.awt.Color(164, 209, 209));

        tfUnit2.setBackground(new java.awt.Color(36, 47, 54));
        tfUnit2.setForeground(new java.awt.Color(164, 209, 209));

        tfname.setBackground(new java.awt.Color(51, 51, 51));
        tfname.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfname.setForeground(new java.awt.Color(164, 209, 209));
        tfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnameActionPerformed(evt);
            }
        });

        tfParent.setBackground(new java.awt.Color(51, 51, 51));
        tfParent.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfParent.setForeground(new java.awt.Color(164, 209, 209));
        tfParent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfParentActionPerformed(evt);
            }
        });

        tfParentContact.setBackground(new java.awt.Color(51, 51, 51));
        tfParentContact.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfParentContact.setForeground(new java.awt.Color(164, 209, 209));
        tfParentContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfParentContactActionPerformed(evt);
            }
        });

        tfDateOfBirth.setBackground(new java.awt.Color(51, 51, 51));
        tfDateOfBirth.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfDateOfBirth.setForeground(new java.awt.Color(164, 209, 209));
        tfDateOfBirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDateOfBirthActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(164, 209, 209));
        jLabel2.setText("Name:");

        jLabel3.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(164, 209, 209));
        jLabel3.setText("Guardian/ Parent Name:");

        jLabel5.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(164, 209, 209));
        jLabel5.setText("Guardian Contact");

        jLabel6.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(164, 209, 209));
        jLabel6.setText("Datbe Of Birth");

        jLabel7.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(164, 209, 209));
        jLabel7.setText("Sex");

        jLabel8.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(164, 209, 209));
        jLabel8.setText("Home Town");

        jLabel9.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(164, 209, 209));
        jLabel9.setText("Religion");

        tfCountryOfOrigin.setBackground(new java.awt.Color(51, 51, 51));
        tfCountryOfOrigin.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfCountryOfOrigin.setForeground(new java.awt.Color(164, 209, 209));
        tfCountryOfOrigin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCountryOfOriginActionPerformed(evt);
            }
        });

        tfHometown.setBackground(new java.awt.Color(51, 51, 51));
        tfHometown.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfHometown.setForeground(new java.awt.Color(164, 209, 209));
        tfHometown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHometownActionPerformed(evt);
            }
        });

        tfReligion.setBackground(new java.awt.Color(51, 51, 51));
        tfReligion.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfReligion.setForeground(new java.awt.Color(164, 209, 209));
        tfReligion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfReligionActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(164, 209, 209));
        jLabel12.setText("Country of Orign");

        jLabel13.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(164, 209, 209));
        jLabel13.setText("Program Code");

        tfProgramName.setBackground(new java.awt.Color(51, 51, 51));
        tfProgramName.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfProgramName.setForeground(new java.awt.Color(164, 209, 209));
        tfProgramName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfProgramNameActionPerformed(evt);
            }
        });

        tfProgramCode.setBackground(new java.awt.Color(51, 51, 51));
        tfProgramCode.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfProgramCode.setForeground(new java.awt.Color(164, 209, 209));
        tfProgramCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfProgramCodeActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(164, 209, 209));
        jLabel14.setText("Program Name");

        jLabel15.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(164, 209, 209));
        jLabel15.setText("Reg. Number");

        tfRegNumber.setBackground(new java.awt.Color(51, 51, 51));
        tfRegNumber.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfRegNumber.setForeground(new java.awt.Color(164, 209, 209));
        tfRegNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRegNumberActionPerformed(evt);
            }
        });

        pfPassword.setBackground(new java.awt.Color(51, 51, 51));
        pfPassword.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        pfPassword.setForeground(new java.awt.Color(164, 209, 209));
        pfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfPasswordActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(164, 209, 209));
        jLabel17.setText("Password");

        cbSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gender?", "Male", "Female" }));
        cbSex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSexActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(26, 59, 80));
        jButton1.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\Student_Management_System\\src\\images\\icons\\icons8-add-user-male-50.png")); // NOI18N
        jButton1.setText("Add Student");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(164, 209, 209));
        jLabel16.setText("  Back");

        lblBack.setBackground(new java.awt.Color(51, 51, 51));
        lblBack.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\Student_Management_System\\src\\images\\icons\\back icon.png")); // NOI18N
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(164, 209, 209));
        jLabel10.setText("Unit code");

        tfUnit1Name.setBackground(new java.awt.Color(51, 51, 51));
        tfUnit1Name.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfUnit1Name.setForeground(new java.awt.Color(164, 209, 209));
        tfUnit1Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnit1NameActionPerformed(evt);
            }
        });

        tfUnit2Name.setBackground(new java.awt.Color(51, 51, 51));
        tfUnit2Name.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfUnit2Name.setForeground(new java.awt.Color(164, 209, 209));
        tfUnit2Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnit2NameActionPerformed(evt);
            }
        });

        tfUnit3Name.setBackground(new java.awt.Color(51, 51, 51));
        tfUnit3Name.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfUnit3Name.setForeground(new java.awt.Color(164, 209, 209));
        tfUnit3Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnit3NameActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(164, 209, 209));
        jLabel18.setText("Unit Name");

        tfUnit4Name.setBackground(new java.awt.Color(51, 51, 51));
        tfUnit4Name.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfUnit4Name.setForeground(new java.awt.Color(164, 209, 209));
        tfUnit4Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnit4NameActionPerformed(evt);
            }
        });

        tfUnit5Name.setBackground(new java.awt.Color(51, 51, 51));
        tfUnit5Name.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfUnit5Name.setForeground(new java.awt.Color(164, 209, 209));
        tfUnit5Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnit5NameActionPerformed(evt);
            }
        });

        tfUnit4Id.setBackground(new java.awt.Color(51, 51, 51));
        tfUnit4Id.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfUnit4Id.setForeground(new java.awt.Color(164, 209, 209));
        tfUnit4Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnit4IdActionPerformed(evt);
            }
        });

        tfUnit5Id.setBackground(new java.awt.Color(51, 51, 51));
        tfUnit5Id.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfUnit5Id.setForeground(new java.awt.Color(164, 209, 209));
        tfUnit5Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnit5IdActionPerformed(evt);
            }
        });

        tfUnit1Id.setBackground(new java.awt.Color(51, 51, 51));
        tfUnit1Id.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfUnit1Id.setForeground(new java.awt.Color(164, 209, 209));
        tfUnit1Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnit1IdActionPerformed(evt);
            }
        });

        tfUnit2Id.setBackground(new java.awt.Color(51, 51, 51));
        tfUnit2Id.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfUnit2Id.setForeground(new java.awt.Color(164, 209, 209));
        tfUnit2Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnit2IdActionPerformed(evt);
            }
        });

        tfUnit3Id.setBackground(new java.awt.Color(51, 51, 51));
        tfUnit3Id.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfUnit3Id.setForeground(new java.awt.Color(164, 209, 209));
        tfUnit3Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnit3IdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tfUnit2Layout = new javax.swing.GroupLayout(tfUnit2);
        tfUnit2.setLayout(tfUnit2Layout);
        tfUnit2Layout.setHorizontalGroup(
            tfUnit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tfUnit2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(tfUnit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(tfUnit2Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(tfUnit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tfUnit2Layout.createSequentialGroup()
                        .addGroup(tfUnit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tfUnit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfUnit4Name, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfUnit1Name)
                                .addComponent(tfUnit2Name, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfUnit3Name, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfUnit5Name, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tfUnit2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)))
                        .addGap(30, 30, 30)
                        .addGroup(tfUnit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfUnit1Id)
                            .addComponent(tfUnit2Id)
                            .addComponent(tfUnit3Id)
                            .addComponent(tfUnit4Id)
                            .addComponent(tfUnit5Id, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tfUnit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(tfUnit2Layout.createSequentialGroup()
                            .addGroup(tfUnit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(27, 27, 27)
                            .addGroup(tfUnit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfProgramName, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfProgramCode, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                            .addGroup(tfUnit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17))
                            .addGap(27, 27, 27)
                            .addGroup(tfUnit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfRegNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(tfUnit2Layout.createSequentialGroup()
                            .addGroup(tfUnit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                            .addGroup(tfUnit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfParent)
                                .addComponent(tfParentContact)
                                .addComponent(tfname, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tfDateOfBirth)
                                .addComponent(cbSex, 0, 182, Short.MAX_VALUE))
                            .addGroup(tfUnit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tfUnit2Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tfUnit2Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tfUnit2Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)))
                            .addGroup(tfUnit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfCountryOfOrigin, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tfHometown)
                                .addComponent(tfReligion, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tfUnit2Layout.setVerticalGroup(
            tfUnit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tfUnit2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(tfUnit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tfUnit2Layout.createSequentialGroup()
                        .addGroup(tfUnit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCountryOfOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tfUnit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfHometown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tfUnit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfReligion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(tfUnit2Layout.createSequentialGroup()
                        .addGroup(tfUnit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(tfUnit2Layout.createSequentialGroup()
                                .addGroup(tfUnit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(tfUnit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfParent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfParentContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tfUnit2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tfUnit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tfUnit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cbSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(47, 47, 47)
                .addGroup(tfUnit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tfUnit2Layout.createSequentialGroup()
                        .addGroup(tfUnit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(tfRegNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tfUnit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tfUnit2Layout.createSequentialGroup()
                        .addGroup(tfUnit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfProgramName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(tfUnit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfProgramCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))))
                .addGap(63, 63, 63)
                .addGroup(tfUnit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tfUnit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tfUnit2Layout.createSequentialGroup()
                        .addComponent(tfUnit1Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfUnit2Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfUnit3Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfUnit4Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfUnit5Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tfUnit2Layout.createSequentialGroup()
                        .addComponent(tfUnit1Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfUnit2Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfUnit3Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfUnit4Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfUnit5Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(tfUnit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBack, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(41, 73, 94));

        jLabel1.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(164, 209, 209));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\Student_Management_System\\src\\images\\icons\\icons8-add-friend-58.png")); // NOI18N
        jLabel1.setText("Register Student");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(tfUnit2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfUnit2, javax.swing.GroupLayout.PREFERRED_SIZE, 676, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfProgramCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfProgramCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfProgramCodeActionPerformed

    private void tfProgramNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfProgramNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfProgramNameActionPerformed

    private void tfReligionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfReligionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfReligionActionPerformed

    private void tfHometownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHometownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHometownActionPerformed

    private void tfCountryOfOriginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCountryOfOriginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCountryOfOriginActionPerformed

    private void tfDateOfBirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDateOfBirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDateOfBirthActionPerformed

    private void tfParentContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfParentContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfParentContactActionPerformed

    private void tfParentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfParentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfParentActionPerformed

    private void tfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnameActionPerformed

    private void tfRegNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRegNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRegNumberActionPerformed

    private void pfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfPasswordActionPerformed

    private void cbSexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSexActionPerformed
        // TODO add your handling code here:
        String sex=cbSex.getSelectedItem().toString();
    }//GEN-LAST:event_cbSexActionPerformed

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        // TODO add your handling code here:
        AdminPage admp = new AdminPage();
        admp.show();
        dispose();
    }//GEN-LAST:event_lblBackMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sex=cbSex.getSelectedItem().toString();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/student_management_system", "root", "emarshKmax");
           // String sql="INSERT into student (regno, tfName, parentname, parentcontact, DOB, sex,countryOfOrigin, hometown, religion, programName, programId ) VALUES (?,?,?,?,?,?,?,?,?,?,?)";
            Statement st = con.createStatement();
             String regno = tfRegNumber.getText();
             String name = tfname.getText();
             String parentname = tfParent.getText();
             String parentcontact = tfParentContact.getText();
             String dob = tfDateOfBirth.getText();
             String gender = (String)cbSex.getSelectedItem();
             String countryOfOrigin = tfCountryOfOrigin.getText();
             String hometown = tfHometown.getText();
             String religion  = tfReligion.getText();
             String programName = tfProgramName.getText();
             String programId = tfProgramCode.getText();
             String password = pfPassword.getText();
             String unitiname = tfUnit1Name.getText();
             String unit1Id= tfUnit1Id.getText();
             String unit2name= tfUnit2Name.getText();
             String unit2Id= tfUnit2Id.getText();
             String unit3name= tfUnit3Name.getText();
             String unit3Id= tfUnit3Id.getText();
             String unit4name= tfUnit4Name.getText();
             String unit14d= tfUnit4Id.getText();
             String unit5name= tfUnit5Name.getText();
             String unit5id= tfUnit5Id.getText();
             st.executeUpdate("insert into student (regno, tfName, parentname, parentcontact, DOB, sex,countryOfOrigin, hometown, religion, programName, programId, password) values("+"\""+regno+"\""+","+"\""+name+"\""+","+"\""+parentname+"\""+","+"\""+parentcontact+"\""+","+"\""+dob+"\""+","+"\""+gender+"\""+","+"\""+countryOfOrigin+"\""+","+"\""+hometown+"\""+","+"\""+religion+"\""+","+"\""+programName+"\""+","+"\""+programId+"\""+","+"\""+password+"\""+");");
            
           /* PreparedStatement pst=conn.prepareStatement(sql);
            pst.setString(1,tfRegNumber.getText());
            pst.setString(2,tfname.getText());
            pst.setString(3,tfParent.getText());
            pst.setString(4, tfParentContact.getText());
            pst.setString(5, tfDateOfBirth.getText());
            pst.setString(6, (String) cbSex.getSelectedItem());
            pst.setString(7,tfCountryOfOrigin.getText());
            pst.setString(8,tfHometown.getText());
            pst.setString(9,tfReligion.getText());
            pst.setString(10,tfProgramName.getText());
            pst.setString(11,tfProgramCode.getText());
            int rowsInserted=pst.executeUpdate();   */
           // if(rowsinserted>0){
                JOptionPane.showMessageDialog(null,"Student Added Succesfully");
                
            //}
          //else  {
            //    JOptionPane.showMessageDialog(null,"Error Adding Student" );
            //}
           
            con.close();
            st.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfUnit1NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnit1NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnit1NameActionPerformed

    private void tfUnit2NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnit2NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnit2NameActionPerformed

    private void tfUnit3NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnit3NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnit3NameActionPerformed

    private void tfUnit4NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnit4NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnit4NameActionPerformed

    private void tfUnit5NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnit5NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnit5NameActionPerformed

    private void tfUnit4IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnit4IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnit4IdActionPerformed

    private void tfUnit5IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnit5IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnit5IdActionPerformed

    private void tfUnit1IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnit1IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnit1IdActionPerformed

    private void tfUnit2IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnit2IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnit2IdActionPerformed

    private void tfUnit3IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnit3IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnit3IdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbSex;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel lblBack;
    private javax.swing.JTextField pfPassword;
    private javax.swing.JTextField tfCountryOfOrigin;
    private javax.swing.JTextField tfDateOfBirth;
    private javax.swing.JTextField tfHometown;
    private javax.swing.JTextField tfParent;
    private javax.swing.JTextField tfParentContact;
    private javax.swing.JTextField tfProgramCode;
    private javax.swing.JTextField tfProgramName;
    private javax.swing.JTextField tfRegNumber;
    private javax.swing.JTextField tfReligion;
    private javax.swing.JTextField tfUnit1Id;
    private javax.swing.JTextField tfUnit1Name;
    private javax.swing.JPanel tfUnit2;
    private javax.swing.JTextField tfUnit2Id;
    private javax.swing.JTextField tfUnit2Name;
    private javax.swing.JTextField tfUnit3Id;
    private javax.swing.JTextField tfUnit3Name;
    private javax.swing.JTextField tfUnit4Id;
    private javax.swing.JTextField tfUnit4Name;
    private javax.swing.JTextField tfUnit5Id;
    private javax.swing.JTextField tfUnit5Name;
    private javax.swing.JTextField tfname;
    // End of variables declaration//GEN-END:variables
}
