/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package student_management_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Marshal
 */
public class Marks extends javax.swing.JFrame {

    /**
     * Creates new form Marks
     */
    public Marks() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfUnit5Id1 = new javax.swing.JTextField();
        tfUnit1Id1 = new javax.swing.JTextField();
        tfUnit2Id1 = new javax.swing.JTextField();
        tfUnit3Id1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfUnit1Name1 = new javax.swing.JTextField();
        tfUnit2Name1 = new javax.swing.JTextField();
        tfUnit3Name1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tfUnit4Name1 = new javax.swing.JTextField();
        tfUnit5Name1 = new javax.swing.JTextField();
        tfUnit4Id1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnAddLecturer = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tfStudentRegNo = new javax.swing.JLabel();
        tfStudentName = new javax.swing.JTextField();
        tfStudentregNo = new javax.swing.JTextField();
        tfUnit5Id = new javax.swing.JTextField();
        tfUnit1Id = new javax.swing.JTextField();
        tfUnit2Id = new javax.swing.JTextField();
        tfUnit3Id = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfUnit1Name = new javax.swing.JTextField();
        tfUnit2Name = new javax.swing.JTextField();
        tfUnit3Name = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        tfUnit4Name = new javax.swing.JTextField();
        tfUnit5Name = new javax.swing.JTextField();
        tfUnit4Id = new javax.swing.JTextField();
        tfExam1 = new javax.swing.JTextField();
        tfExam2 = new javax.swing.JTextField();
        tfExam3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tfCat1 = new javax.swing.JTextField();
        tfCat2 = new javax.swing.JTextField();
        tfCat3 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        tfCat4 = new javax.swing.JTextField();
        tfCat5 = new javax.swing.JTextField();
        tfExam4 = new javax.swing.JTextField();
        tfExam5 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tfStudentRegNo1 = new javax.swing.JLabel();
        tfProgramName = new javax.swing.JTextField();
        tfProgramCode = new javax.swing.JTextField();

        tfUnit5Id1.setBackground(new java.awt.Color(51, 51, 51));
        tfUnit5Id1.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfUnit5Id1.setForeground(new java.awt.Color(164, 209, 209));
        tfUnit5Id1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnit5Id1ActionPerformed(evt);
            }
        });

        tfUnit1Id1.setBackground(new java.awt.Color(51, 51, 51));
        tfUnit1Id1.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfUnit1Id1.setForeground(new java.awt.Color(164, 209, 209));
        tfUnit1Id1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnit1Id1ActionPerformed(evt);
            }
        });

        tfUnit2Id1.setBackground(new java.awt.Color(51, 51, 51));
        tfUnit2Id1.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfUnit2Id1.setForeground(new java.awt.Color(164, 209, 209));
        tfUnit2Id1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnit2Id1ActionPerformed(evt);
            }
        });

        tfUnit3Id1.setBackground(new java.awt.Color(51, 51, 51));
        tfUnit3Id1.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfUnit3Id1.setForeground(new java.awt.Color(164, 209, 209));
        tfUnit3Id1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnit3Id1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(164, 209, 209));
        jLabel10.setText("Unit code");

        tfUnit1Name1.setBackground(new java.awt.Color(51, 51, 51));
        tfUnit1Name1.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfUnit1Name1.setForeground(new java.awt.Color(164, 209, 209));
        tfUnit1Name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnit1Name1ActionPerformed(evt);
            }
        });

        tfUnit2Name1.setBackground(new java.awt.Color(51, 51, 51));
        tfUnit2Name1.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfUnit2Name1.setForeground(new java.awt.Color(164, 209, 209));
        tfUnit2Name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnit2Name1ActionPerformed(evt);
            }
        });

        tfUnit3Name1.setBackground(new java.awt.Color(51, 51, 51));
        tfUnit3Name1.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfUnit3Name1.setForeground(new java.awt.Color(164, 209, 209));
        tfUnit3Name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnit3Name1ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(164, 209, 209));
        jLabel18.setText("Unit Name");

        tfUnit4Name1.setBackground(new java.awt.Color(51, 51, 51));
        tfUnit4Name1.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfUnit4Name1.setForeground(new java.awt.Color(164, 209, 209));
        tfUnit4Name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnit4Name1ActionPerformed(evt);
            }
        });

        tfUnit5Name1.setBackground(new java.awt.Color(51, 51, 51));
        tfUnit5Name1.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfUnit5Name1.setForeground(new java.awt.Color(164, 209, 209));
        tfUnit5Name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnit5Name1ActionPerformed(evt);
            }
        });

        tfUnit4Id1.setBackground(new java.awt.Color(51, 51, 51));
        tfUnit4Id1.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfUnit4Id1.setForeground(new java.awt.Color(164, 209, 209));
        tfUnit4Id1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnit4Id1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(36, 47, 54));

        jPanel3.setBackground(new java.awt.Color(41, 73, 94));
        jPanel3.setForeground(new java.awt.Color(164, 209, 209));

        jLabel1.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(164, 209, 209));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\Student_Management_System\\src\\images\\icons\\report.png")); // NOI18N
        jLabel1.setText("Enter Student Marks");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N

        btnAddLecturer.setBackground(new java.awt.Color(26, 59, 80));
        btnAddLecturer.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        btnAddLecturer.setForeground(new java.awt.Color(0, 0, 0));
        btnAddLecturer.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\Student_Management_System\\src\\images\\icons\\icons8-report-card-50.png")); // NOI18N
        btnAddLecturer.setText("Commit Marks");
        btnAddLecturer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAddLecturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLecturerActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(164, 209, 209));
        jLabel12.setText("  Back");

        lblBack.setBackground(new java.awt.Color(0, 0, 0));
        lblBack.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\Student_Management_System\\src\\images\\icons\\back icon.png")); // NOI18N
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(164, 209, 209));
        jLabel14.setText("Student Name");

        tfStudentRegNo.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfStudentRegNo.setForeground(new java.awt.Color(164, 209, 209));
        tfStudentRegNo.setText("Student RegNo.");

        tfStudentName.setBackground(new java.awt.Color(51, 51, 51));
        tfStudentName.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfStudentName.setForeground(new java.awt.Color(164, 209, 209));
        tfStudentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStudentNameActionPerformed(evt);
            }
        });

        tfStudentregNo.setBackground(new java.awt.Color(51, 51, 51));
        tfStudentregNo.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfStudentregNo.setForeground(new java.awt.Color(164, 209, 209));
        tfStudentregNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStudentregNoActionPerformed(evt);
            }
        });

        tfUnit5Id.setBackground(new java.awt.Color(51, 51, 51));
        tfUnit5Id.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfUnit5Id.setForeground(new java.awt.Color(164, 209, 209));
        tfUnit5Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnit5IdActionPerformed(evt);
            }
        });

        tfUnit1Id.setBackground(new java.awt.Color(51, 51, 51));
        tfUnit1Id.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfUnit1Id.setForeground(new java.awt.Color(164, 209, 209));
        tfUnit1Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnit1IdActionPerformed(evt);
            }
        });

        tfUnit2Id.setBackground(new java.awt.Color(51, 51, 51));
        tfUnit2Id.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfUnit2Id.setForeground(new java.awt.Color(164, 209, 209));
        tfUnit2Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnit2IdActionPerformed(evt);
            }
        });

        tfUnit3Id.setBackground(new java.awt.Color(51, 51, 51));
        tfUnit3Id.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfUnit3Id.setForeground(new java.awt.Color(164, 209, 209));
        tfUnit3Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnit3IdActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(164, 209, 209));
        jLabel11.setText("Unit code");

        tfUnit1Name.setBackground(new java.awt.Color(51, 51, 51));
        tfUnit1Name.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfUnit1Name.setForeground(new java.awt.Color(164, 209, 209));
        tfUnit1Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnit1NameActionPerformed(evt);
            }
        });

        tfUnit2Name.setBackground(new java.awt.Color(51, 51, 51));
        tfUnit2Name.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfUnit2Name.setForeground(new java.awt.Color(164, 209, 209));
        tfUnit2Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnit2NameActionPerformed(evt);
            }
        });

        tfUnit3Name.setBackground(new java.awt.Color(51, 51, 51));
        tfUnit3Name.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfUnit3Name.setForeground(new java.awt.Color(164, 209, 209));
        tfUnit3Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnit3NameActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(164, 209, 209));
        jLabel27.setText("Unit Name");

        tfUnit4Name.setBackground(new java.awt.Color(51, 51, 51));
        tfUnit4Name.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfUnit4Name.setForeground(new java.awt.Color(164, 209, 209));
        tfUnit4Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnit4NameActionPerformed(evt);
            }
        });

        tfUnit5Name.setBackground(new java.awt.Color(51, 51, 51));
        tfUnit5Name.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfUnit5Name.setForeground(new java.awt.Color(164, 209, 209));
        tfUnit5Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnit5NameActionPerformed(evt);
            }
        });

        tfUnit4Id.setBackground(new java.awt.Color(51, 51, 51));
        tfUnit4Id.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfUnit4Id.setForeground(new java.awt.Color(164, 209, 209));
        tfUnit4Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnit4IdActionPerformed(evt);
            }
        });

        tfExam1.setBackground(new java.awt.Color(51, 51, 51));
        tfExam1.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfExam1.setForeground(new java.awt.Color(164, 209, 209));
        tfExam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfExam1ActionPerformed(evt);
            }
        });

        tfExam2.setBackground(new java.awt.Color(51, 51, 51));
        tfExam2.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfExam2.setForeground(new java.awt.Color(164, 209, 209));
        tfExam2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfExam2ActionPerformed(evt);
            }
        });

        tfExam3.setBackground(new java.awt.Color(51, 51, 51));
        tfExam3.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfExam3.setForeground(new java.awt.Color(164, 209, 209));
        tfExam3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfExam3ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(164, 209, 209));
        jLabel13.setText("Exam Marks(x/70)");

        tfCat1.setBackground(new java.awt.Color(51, 51, 51));
        tfCat1.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfCat1.setForeground(new java.awt.Color(164, 209, 209));
        tfCat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCat1ActionPerformed(evt);
            }
        });

        tfCat2.setBackground(new java.awt.Color(51, 51, 51));
        tfCat2.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfCat2.setForeground(new java.awt.Color(164, 209, 209));
        tfCat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCat2ActionPerformed(evt);
            }
        });

        tfCat3.setBackground(new java.awt.Color(51, 51, 51));
        tfCat3.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfCat3.setForeground(new java.awt.Color(164, 209, 209));
        tfCat3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCat3ActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(164, 209, 209));
        jLabel28.setText("Cat Marks (x/30)");

        tfCat4.setBackground(new java.awt.Color(51, 51, 51));
        tfCat4.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfCat4.setForeground(new java.awt.Color(164, 209, 209));
        tfCat4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCat4ActionPerformed(evt);
            }
        });

        tfCat5.setBackground(new java.awt.Color(51, 51, 51));
        tfCat5.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfCat5.setForeground(new java.awt.Color(164, 209, 209));
        tfCat5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCat5ActionPerformed(evt);
            }
        });

        tfExam4.setBackground(new java.awt.Color(51, 51, 51));
        tfExam4.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfExam4.setForeground(new java.awt.Color(164, 209, 209));
        tfExam4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfExam4ActionPerformed(evt);
            }
        });

        tfExam5.setBackground(new java.awt.Color(51, 51, 51));
        tfExam5.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfExam5.setForeground(new java.awt.Color(164, 209, 209));
        tfExam5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfExam5ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(164, 209, 209));
        jLabel15.setText("Program Name");

        tfStudentRegNo1.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfStudentRegNo1.setForeground(new java.awt.Color(164, 209, 209));
        tfStudentRegNo1.setText("ProgramId");

        tfProgramName.setBackground(new java.awt.Color(51, 51, 51));
        tfProgramName.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfProgramName.setForeground(new java.awt.Color(164, 209, 209));
        tfProgramName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfProgramNameActionPerformed(evt);
            }
        });

        tfProgramCode.setBackground(new java.awt.Color(51, 51, 51));
        tfProgramCode.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        tfProgramCode.setForeground(new java.awt.Color(164, 209, 209));
        tfProgramCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfProgramCodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfStudentRegNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfStudentregNo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tfUnit4Name, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfUnit1Name)
                                        .addComponent(tfUnit2Name, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfUnit3Name, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfUnit5Name, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(91, 91, 91)))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfUnit1Id)
                                    .addComponent(tfUnit2Id)
                                    .addComponent(tfUnit3Id)
                                    .addComponent(tfUnit4Id)
                                    .addComponent(tfUnit5Id, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tfCat5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                        .addComponent(tfCat4, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfCat3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfCat2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfCat1, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tfExam5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                        .addComponent(tfExam4, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfExam3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfExam2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfExam1, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfStudentRegNo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfProgramName, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfProgramCode, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 240, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(173, 173, 173))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddLecturer, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfStudentregNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfStudentRegNo))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfProgramName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfProgramCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfStudentRegNo1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(tfUnit1Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfUnit2Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfUnit3Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfUnit4Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfUnit5Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(tfUnit1Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfUnit2Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfUnit3Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfUnit4Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfUnit5Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(tfCat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfCat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfCat3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfCat4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfCat5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(tfExam1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfExam2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfExam3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfExam4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfExam5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                        .addComponent(lblBack, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddLecturer, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddLecturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLecturerActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/student_management_system", "root", "emarshKmax");
            // String sql="INSERT into student (regno, tfName, parentname, parentcontact, DOB, sex,countryOfOrigin, hometown, religion, programName, programId ) VALUES (?,?,?,?,?,?,?,?,?,?,?)";
            Statement st = con.createStatement();

            String studentName = tfStudentName.getText();
            String studentRegNo = tfStudentregNo.getText();
            String programName= tfProgramName.getText();
            String programId = tfProgramCode.getText();
            String unit1name = tfUnit1Name.getText();
            String unit1Id= tfUnit1Id.getText();
            String unit2name= tfUnit2Name.getText();
            String unit2Id= tfUnit2Id.getText();
            String unit3name= tfUnit3Name.getText();
            String unit3Id= tfUnit3Id.getText();
            String unit4name= tfUnit4Name.getText();
            String unit4Id= tfUnit4Id.getText();
            String unit5name= tfUnit5Name.getText();
            String unit5id= tfUnit5Id.getText();
            
            String cat1= tfCat1.getText();
            String cat2= tfCat2.getText();
            String cat3= tfCat3.getText();
            String cat4= tfCat4.getText();
            String cat5= tfCat5.getText();
            
            String exam1= tfExam1.getText();
            String exam2= tfExam2.getText();
            String exam3= tfExam3.getText();
            String exam4 = tfExam4.getText();
            String exam5= tfExam5.getText();
            
            
                    
            
                        
            st.executeUpdate("insert into exam (ProgramName, ProgramId, Unit1Name, Unit1Id, Unit2Name, Unit2Id, Unit3Name, Unit3Id, Unit4Name, Unit4Id, Unit5Name, Unit5Id, Cat1, Cat2, Cat3, Cat4, Cat5, Exam1, Exam2, Exam3, Exam4, Exam5, StudentName, StudentRegNo) values("+"\""+programId+"\""+","+"\""+programName+"\""+","+"\""+unit1name+"\""+","+"\""+unit1Id+"\""+","+"\""+unit2name+"\""+","+"\""+unit2Id+"\""+","+"\""+unit3name+"\""+","+"\""+unit3Id+"\""+","+"\""+unit4name+"\""+","+"\""+unit4Id+"\""+","+"\""+unit5name+"\""+","+"\""+unit5id+"\""+","+"\""+exam1+"\""+","+"\""+exam2+"\""+","+"\""+exam3+"\""+","+"\""+exam4+"\""+","+"\""+exam5+"\""+","+"\""+cat1+"\""+","+"\""+cat2+"\""+","+"\""+cat3+"\""+","+"\""+cat4+"\""+","+"\""+cat5+"\""+","+"\""+studentName+"\""+","+"\""+studentRegNo+"\""+")");

            
                JOptionPane.showMessageDialog(null,"Marks Commited Succesfully");

             

            con.close();
            st.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_btnAddLecturerActionPerformed

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        // TODO add your handling code here:
        AdminPage admp = new AdminPage();
        admp.show();
        dispose();
    }//GEN-LAST:event_lblBackMouseClicked

    private void tfStudentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStudentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStudentNameActionPerformed

    private void tfStudentregNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStudentregNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStudentregNoActionPerformed

    private void tfUnit5Id1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnit5Id1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnit5Id1ActionPerformed

    private void tfUnit1Id1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnit1Id1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnit1Id1ActionPerformed

    private void tfUnit2Id1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnit2Id1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnit2Id1ActionPerformed

    private void tfUnit3Id1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnit3Id1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnit3Id1ActionPerformed

    private void tfUnit1Name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnit1Name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnit1Name1ActionPerformed

    private void tfUnit2Name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnit2Name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnit2Name1ActionPerformed

    private void tfUnit3Name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnit3Name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnit3Name1ActionPerformed

    private void tfUnit4Name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnit4Name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnit4Name1ActionPerformed

    private void tfUnit5Name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnit5Name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnit5Name1ActionPerformed

    private void tfUnit4Id1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnit4Id1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnit4Id1ActionPerformed

    private void tfUnit5IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnit5IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnit5IdActionPerformed

    private void tfUnit1IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnit1IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnit1IdActionPerformed

    private void tfUnit2IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnit2IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnit2IdActionPerformed

    private void tfUnit3IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnit3IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnit3IdActionPerformed

    private void tfUnit1NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnit1NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnit1NameActionPerformed

    private void tfUnit2NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnit2NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnit2NameActionPerformed

    private void tfUnit3NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnit3NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnit3NameActionPerformed

    private void tfUnit4NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnit4NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnit4NameActionPerformed

    private void tfUnit5NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnit5NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnit5NameActionPerformed

    private void tfUnit4IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnit4IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnit4IdActionPerformed

    private void tfCat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCat1ActionPerformed

    private void tfCat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCat2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCat2ActionPerformed

    private void tfCat3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCat3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCat3ActionPerformed

    private void tfCat4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCat4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCat4ActionPerformed

    private void tfCat5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCat5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCat5ActionPerformed

    private void tfExam3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfExam3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfExam3ActionPerformed

    private void tfExam2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfExam2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfExam2ActionPerformed

    private void tfExam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfExam1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfExam1ActionPerformed

    private void tfExam5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfExam5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfExam5ActionPerformed

    private void tfExam4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfExam4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfExam4ActionPerformed

    private void tfProgramNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfProgramNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfProgramNameActionPerformed

    private void tfProgramCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfProgramCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfProgramCodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Marks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Marks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Marks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Marks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Marks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddLecturer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblBack;
    private javax.swing.JTextField tfCat1;
    private javax.swing.JTextField tfCat2;
    private javax.swing.JTextField tfCat3;
    private javax.swing.JTextField tfCat4;
    private javax.swing.JTextField tfCat5;
    private javax.swing.JTextField tfExam1;
    private javax.swing.JTextField tfExam2;
    private javax.swing.JTextField tfExam3;
    private javax.swing.JTextField tfExam4;
    private javax.swing.JTextField tfExam5;
    private javax.swing.JTextField tfProgramCode;
    private javax.swing.JTextField tfProgramName;
    private javax.swing.JTextField tfStudentName;
    private javax.swing.JLabel tfStudentRegNo;
    private javax.swing.JLabel tfStudentRegNo1;
    private javax.swing.JTextField tfStudentregNo;
    private javax.swing.JTextField tfUnit1Id;
    private javax.swing.JTextField tfUnit1Id1;
    private javax.swing.JTextField tfUnit1Name;
    private javax.swing.JTextField tfUnit1Name1;
    private javax.swing.JTextField tfUnit2Id;
    private javax.swing.JTextField tfUnit2Id1;
    private javax.swing.JTextField tfUnit2Name;
    private javax.swing.JTextField tfUnit2Name1;
    private javax.swing.JTextField tfUnit3Id;
    private javax.swing.JTextField tfUnit3Id1;
    private javax.swing.JTextField tfUnit3Name;
    private javax.swing.JTextField tfUnit3Name1;
    private javax.swing.JTextField tfUnit4Id;
    private javax.swing.JTextField tfUnit4Id1;
    private javax.swing.JTextField tfUnit4Name;
    private javax.swing.JTextField tfUnit4Name1;
    private javax.swing.JTextField tfUnit5Id;
    private javax.swing.JTextField tfUnit5Id1;
    private javax.swing.JTextField tfUnit5Name;
    private javax.swing.JTextField tfUnit5Name1;
    // End of variables declaration//GEN-END:variables
}
